/* Original linked frontier narrative. Milestones refer to playable game events. */
(function(root){
const arcs=[
 {id:'water',title:'The Water Ledger',speaker:'Ivo Rook',requires:[],brief:'Someone is buying water for people who no longer exist. Twelve manifests, twelve dead captains, every payment cleared by the same New York office. Rook has been hauling the tanks without asking questions. Last night a girl in the freight queue called him by one of those dead captains’ names. He wants to know who taught her.',steps:[
  ['terminal','Earth','Read a city operations terminal on Earth','The manifests are genuine. The names are borrowed. A clerk has been routing subsidized shipments through dead accounts to keep an unregistered Martian district alive. The discrepancy is not where the water went; it is who sold the district’s right to buy it.'],
  ['delivery','Mars','Deliver four organics at a Martian port','The cargo includes membrane cultures for the district’s failing water filters. Rook expected a smuggler. The receiver is a schoolteacher, her register written on the reverse of an eviction notice. “Put their real names on your next invoice,” she says. “If you can afford to.”','organics',4],
  ['terminal','Earth','Return to Earth and read the account authority','Helix bought the concession legally. The Union approved it quietly. Publishing only one signature would make a useful scandal and leave the contract intact. Publishing the whole chain will embarrass the people offering to protect you.']
 ],choices:[['Publish the complete ledger','union',12,650,'The ledger is public, including the Union signatures. Emergency filter supplies reach Mars. Rook starts using his own name on manifests again.',{world:'Mars',good:'organics',stock:45}],['Sell the concession back to its residents','helix',10,1100,'You broker a private transfer. The school keeps its water, Helix keeps the rest of its books closed, and Rook keeps a copy of every signature.',{world:'Mars',good:'organics',stock:24}]]},
 {id:'orchard',title:'The Orchard That Remembers',speaker:'Dr. Mara Sol',requires:[],brief:'A grove on TRAPPIST-1 e has grown around a survey stake placed only six days ago. The tree rings say forty years. Mara does not believe in prophetic trees. She does believe that someone has changed the dating standard—and that the colony’s food contracts were priced using the old one.',steps:[
  ['sample','TRAPPIST-1 e','Collect a surface sample on TRAPPIST-1 e · N','The grove is layered. Older tissue shelters younger shoots from the host star’s activity. The stake did not age the tree. It punctured a living archive, and a contractor called the resulting growth contamination.'],
  ['terminal','TRAPPIST-1 f','Read a laboratory terminal on TRAPPIST-1 f','The laboratory stores the same growth pattern under a patent number. A technician’s note names her mother as the original collector. Her mother’s citizenship was revoked before the patent was filed.'],
  ['delivery','TRAPPIST-1 e','Deliver four organics to the habitat seed bank','Mara can keep a protected sample alive, but protection is also a claim of ownership. The settlers ask for cultures they can propagate themselves. The lab asks you to keep them sterile.','organics',4]
 ],choices:[['Open the seed archive to every habitat','union',14,850,'The culture instructions travel with the samples. No faction can revoke a seed that has already been planted. Mara keeps the collector’s name on the record.',{world:'TRAPPIST-1 e',good:'organics',stock:60}],['Fund a guarded research reserve','helix',12,1300,'The reserve receives power and trained staff. Its gates also receive locks. Mara accepts the funding and insists that the collector’s descendants hold a key.',{world:'TRAPPIST-1 f',good:'crystal',stock:30}]]},
 {id:'furnace',title:'A Sun Inside the Invoice',speaker:'Leonie Park, thermal auditor',requires:[],brief:'A refinery bills three systems for cooling the same tonne of metal. Leonie calls that fraud. Her employer calls it a shared thermal obligation. A maintenance crew on WASP-76 b calls it the reason their next shift may not come home.',steps:[
  ['station','WASP-76 b','Reach the WASP-76 b orbital habitat','The heat balance does not close. A reserve radiator is listed as operational, but the maintenance record says it was sold six months ago. The replacement serial belongs to a reactor controller on K2-141 b.'],
  ['power','K2-141 b','Bring a city reactor online on K2-141 b','The controller contains two calibration tables. One keeps equipment alive; the other meets the export quota. Leonie’s supervisor signed the quota table while his own family was on the safe shift.'],
  ['terminal','WASP-76 b','Read the refinery audit at a WASP-76 b city terminal','The crews want a shutdown and back pay. The outer habitats need this refinery’s output. Leonie will sign either order if you attach your name beside hers. She refuses to sign a third excuse.']
 ],choices:[['Suspend the quota and release the evidence','union',10,950,'Emergency stock buys the crews a maintenance window. Output falls, but the hidden calibration stops deciding who gets to live through a shift.',{world:'WASP-76 b',good:'ore',stock:-35}],['Finance the repair without stopping exports','helix',14,1600,'The Compact funds replacement equipment and pays the crews. The quota survives. Leonie makes the repaired controller transmit its real readings to an open channel.',{world:'K2-141 b',good:'ore',stock:45}]]},
 {id:'missing',title:'The Passenger in the Cargo Hold',speaker:'Tamsin Cho, dock physician',requires:['water'],brief:'A freighter arrived at TOI-270 c with forty-one life-support allocations and forty passengers. Its captain insists the missing allocation belongs to spare parts. Tamsin has heard those spare parts singing through the quarantine wall. The voice knows a childhood song that was never broadcast off Earth.',steps:[
  ['station','TOI-270 c','Reach the quarantine habitat at TOI-270 c','There is no hidden passenger. The “voice” is a medical archive assembled from colonists who sold memory recordings to pay for passage. One recording has identified the physician who falsified their consent forms.'],
  ['terminal','TOI-270 b','Read the consent register on TOI-270 b','The forged forms share the concession office from the water ledger. Rook recognizes its witness code. He signed one of the forms before he knew what the company would do with it.'],
  ['delivery','TOI-270 c','Deliver four crystals for an independent archive copy','The archive asks for storage that can leave quarantine. Tamsin refuses to call a collection of voices a person on command, and refuses to erase it on command either. A copy will let the affected families answer for themselves.','crystal',4]
 ],choices:[['Give custody to the recorded families','union',16,1200,'Families receive copies and the right to withdraw their own recordings. Some preserve them. Some delete them. For the first time, the archive’s silence is a choice.',{world:'TOI-270 c',good:'crystal',stock:20}],['Grant independent custody to the archive','redwake',16,1500,'You route the copy through independent ships. The archive chooses a callsign: Forty-One. Tamsin keeps the consent hearing open, including the difficult questions.',{world:'TOI-270 c',good:'crystal',stock:35}]]},
 {id:'relay',title:'The Quiet Between Storms',speaker:'Jun Mercer, relay keeper',requires:['orchard'],brief:'TRAPPIST-1 g loses a weather relay every time the same convoy leaves port. The official explanation is stellar interference. Jun has serviced those relays for twenty years. Interference, he says, does not wait for the cargo doors to close.',steps:[
  ['power','TRAPPIST-1 g','Restore a city reactor feed on TRAPPIST-1 g','The backup feed reveals a narrow transmission window. The convoy uses storm outages to conceal a route to unlicensed habitats. The people cutting power say the licensed routes charge more than those habitats can pay.'],
  ['combat','TRAPPIST-1 g','Defeat a hostile combatant in a TRAPPIST-1 g encounter','The recovered orders instruct the raiders to destroy antennas, not cargo. Someone bought their discipline. Jun recognizes the payment schedule: it is his own missing maintenance budget.'],
  ['terminal','TRAPPIST-1 e','Read the relay procurement records on TRAPPIST-1 e','The evidence connects the patented orchard, the relay budget, and an insurance fund that profits when remote settlements cannot prove a storm warning was withheld.']
 ],choices:[['Publish a free warning network','union',14,1300,'The habitats receive independent warnings. Smugglers can read them too. Jun would rather broadcast to a thief than let a child miss the evacuation order.',{world:'TRAPPIST-1 g',good:'crystal',stock:35}],['Negotiate protected independent routes','redwake',20,1700,'Independent captains stop cutting relays in exchange for access to the public forecast. Jun logs the agreement under maintenance, where nobody can pretend it was charity.',{world:'TRAPPIST-1 g',good:'organics',stock:40}]]},
 {id:'mirror',title:'The Mirror Fleet',speaker:'Seren Vale',requires:['furnace'],brief:'Neptune’s approach radar has counted the same freighter entering port three times in one minute. The pilots blame reflections. Vale has found three matching freight payments. Someone has taught an accounting system to believe in ghosts.',steps:[
  ['station','Neptune','Reach Neptune’s orbital traffic station','The ghost tracks are old distress telemetry, replayed with new transponders. The missing radiator from Leonie’s audit travelled aboard one of these supposed ships. A salvage cooperative has been collecting docking fees for wrecks.'],
  ['delivery','Earth','Deliver four ore to Earth’s replacement-parts pool','The cooperative used the fees to fabricate parts for abandoned rescue beacons. It also sold the best parts to the highest bidder. Vale refuses to let either fact erase the other.','ore',4],
  ['delivery','Neptune','Deliver four ore for Neptune’s rescue-beacon repairs','Live beacon power separates the genuine distress traffic from the forged fleet. One real ship is still out there. Its last manifest lists the clerk who opened the dead water accounts.','ore',4]
 ],choices:[['Put the rescue beacons in public trust','union',18,1450,'The cooperatives keep their workshops under an audited rescue charter. Vale orders the live distress channel to stay open through the hearing.',{world:'Neptune',good:'ore',stock:35}],['Keep the cooperative independent with restitution','redwake',14,1850,'The cooperative repays the forged fees in parts and publishes its beacon map. Independent captains defend the workshops. The falsified records remain evidence.',{world:'Neptune',good:'ore',stock:50}]]},
 {id:'witness',title:'A Name No One Can Sell',speaker:'Forty-One / Ivo Rook',requires:['missing','mirror'],brief:'The water clerk survived. Her testimony is distributed across a damaged recorder, the passenger archive, and Rook’s memory of a dock he would rather forget. Each witness can prove one part. None can prove the whole transaction alone.',steps:[
  ['terminal','Mars','Recover the district’s original registry on Mars','The district was not abandoned by accident. Its debt was packaged with rights to its residents’ medical records and the salvage value of its supply fleet. The same names appear in all three ledgers.'],
  ['station','TOI-270 c','Meet the custodians of the passenger archive','Forty-One offers the missing timestamp but asks that the families’ recordings remain outside the evidence package. Rook offers his own testimony instead. It is weaker evidence and a risk he finally takes himself.'],
  ['terminal','Earth','Prepare the public hearing record on Earth','The hearing can win a quick conviction by exposing private recordings, or establish a narrower case using voluntary testimony. The residents ask to attend as witnesses, not as data.']
 ],choices:[['Use only testimony its owners volunteer','union',22,1800,'The case takes longer. Some counts fail. The concession itself is voided, and the witnesses leave with the rights the prosecution promised to defend.',{world:'Mars',good:'organics',stock:55}],['Release the full archive under protected review','helix',8,2300,'The review convicts more officials and seals the records afterward. Forty-One records every access request. Trust returns slowly, even where the judgment is welcomed.',{world:'Earth',good:'crystal',stock:40}]]},
 {id:'assembly',title:'The Night Shift Assembly',speaker:'Leonie Park / Jun Mercer',requires:['relay','furnace'],brief:'Refinery crews, relay keepers, growers, and independent captains have called an assembly. None trusts the others to write the charter. Each has also kept someone else alive without being paid. Their first argument is over who gets to turn the lights on.',steps:[
  ['delivery','K2-141 b','Deliver four crystals for the assembly’s independent power bus','The bus removes the host refinery’s ability to cut the meeting short. Leonie takes the first night shift. Jun arrives with weather logs, not a speech.','crystal',4],
  ['terminal','TRAPPIST-1 g','Read the habitat warning charter on TRAPPIST-1 g','The warning network has outgrown its original bargain. Smaller settlements need representation before the large ports sell priority access back to them.'],
  ['station','WASP-76 b','Carry the charter to the refinery habitat','The workers want guaranteed maintenance. The captains want open docks. The growers want reproducible seed. The Compact offers to enforce every guarantee if it owns the switchboard.']
 ],choices:[['Ratify a distributed habitat charter','union',20,2000,'Each habitat controls its local bus; the shared network must publish its tariffs. Disputes remain, but no single switch can silence the assembly.',{world:'K2-141 b',good:'crystal',stock:55}],['Create an independent captains’ mutual','redwake',22,2400,'The captains insure repairs and warning relays collectively. The smallest habitats receive voting shares before the richest ships do. Jun makes that line the first test of the agreement.',{world:'TRAPPIST-1 g',good:'organics',stock:60}]]},
 {id:'patriot',title:'What the Flag Is For',speaker:'Seren Vale',requires:['witness','assembly'],brief:'The frontier has your records, your supply routes, and your compromises. Now every faction wants to put its flag on them. Vale offers a hangar for the signing. “Pick a symbol if you like,” she says. “But tell the night shift what it will do when the next pump fails.”',steps:[
  ['delivery','Mars','Deliver four organics to the first district you helped','The schoolteacher has kept the first invoice. This one has the real residents’ names. She asks you to take a copy to the signing, beside the speeches and the casualty lists.','organics',4],
  ['power','Earth','Bring an Earth city reactor feed online for the meeting','The meeting starts while the public maintenance display is still open. A technician asks the delegates to move their chairs away from the service hatch. They do.'],
  ['terminal','Earth','Open the final charter at an Earth city terminal','Your earlier decisions remain in the journal: who received the seeds, who kept custody of the voices, who paid for repairs. A flag cannot turn those choices into a cleaner story. It can make a promise about the next one.']
 ],choices:[['A frontier with public services and open records','union',25,3200,'The charter funds common rescue, water, warning, and repair services. The signatories keep their factions. The terminals keep their audit logs. Space Patriot continues in a frontier that remembers what your crew changed.',{world:'Earth',good:'organics',stock:90}],['A frontier of independent, mutually bound habitats','redwake',25,3500,'The habitats own their local systems and guarantee reciprocal aid. No captain may collect a rescue debt from a child. The first test is already blinking on the maintenance display.',{world:'Earth',good:'ore',stock:90}]]}
];
function project(){const quests=[],nodes=[];for(const arc of arcs){const id=arc.id,node=(suffix,type,title,extra={})=>({id:id+'-'+suffix,questId:id,type,title,...(type==='dialogue'?{actions:[{type:'journal',text:arc.title+' / '+arc.speaker+' — '+extra.text}]}:{}),...extra});quests.push({id,title:arc.title,entry:id+'-brief',requires:arc.requires.length?{all:arc.requires.map(key=>({source:'quest',key,value:'completed'}))}:undefined});
 nodes.push(node('brief','dialogue',arc.title,{speaker:arc.speaker,text:arc.brief,choices:[{id:'begin',text:'Take the case',next:id+'-step0'}]}));
 arc.steps.forEach((s,i)=>{nodes.push(node('step'+i,'objective',s[2],{event:'gameplay.signal',match:{kind:s[0],world:s[1]},goal:s[0]==='combat'?1:1,next:id+'-report'+i,location:{kind:s[0],world:s[1],good:s[4]||null,units:s[5]||0}}));nodes.push(node('report'+i,'dialogue',arc.title,{speaker:arc.speaker,text:s[3],choices:[{id:'continue',text:'Continue the investigation',next:id+'-'+(i+1<arc.steps.length?'step'+(i+1):'decision')}]}));});
 nodes.push(node('decision','dialogue','Choose the outcome',{speaker:arc.speaker,text:'This decision changes standing, payment, and the supplies available to the affected world. Both records remain in your journal.',choices:arc.choices.map((c,i)=>({id:'choice'+i,text:c[0],next:id+'-end'+i,actions:[{type:'flag',key:id+'-choice'+i,value:true}]}))}));
 arc.choices.forEach((c,i)=>nodes.push(node('end'+i,'end',c[0],{result:'completed',actions:[{type:'journal',text:arc.title+' — '+c[4]},{type:'command',command:'campaign.reward',payload:{key:id,faction:c[1],standing:c[2],credits:c[3],market:c[5]}}]})));
 }return JSON.parse(JSON.stringify({format:'storyworks-project',version:1,id:'space-patriot-long-debt-v1',title:'The Long Debt',variables:{},quests,nodes}));}
root.SpacePatriotCampaign={arcs,project};
})(globalThis);
