(function init(){if(!window.longway)return addEventListener('longway-ready',init,{once:true});const A=longway,C=LongwayCore,P=A.campaign=new C.Campaign(A),key='space-patriot-long-debt-v1';
 try{const s=localStorage.getItem(key);if(s&&s.length<500000)P.load(JSON.parse(s));}catch(e){console.warn('Campaign save could not be loaded',e.message);}
 P.persist=()=>{if(!P.authority)return;try{localStorage.setItem(key,JSON.stringify(P.save()));A.economy.save();localStorage.setItem('space-patriot-society-v1',JSON.stringify(A.society.save()));}catch{A.flight.message='Campaign retained in this session; browser storage unavailable';}};
 addEventListener('beforeunload',P.persist);
 const panel=document.createElement('section');panel.id='campaignPanel';panel.hidden=true;panel.innerHTML='<h2>The Long Debt</h2><p>Nine connected investigations across five systems. Choices change standing and world supplies.</p><div class="campaign-layout"><nav></nav><article><small></small><h3></h3><p class="campaign-text"></p><div class="campaign-actions"></div><details><summary>Persistent case journal</summary><div class="campaign-journal"></div></details></article></div>';document.body.append(panel);BloxUI.registerDialog('campaignPanel');
 const style=document.createElement('style');style.textContent='#campaignPanel .campaign-layout{display:grid;grid-template-columns:220px 1fr;gap:24px}#campaignPanel nav{display:grid;align-content:start;gap:8px}#campaignPanel nav button{text-align:left;padding:12px}#campaignPanel article h3{font:24px Georgia,serif}#campaignPanel .campaign-text{font:16px/1.75 Georgia,serif;max-width:70ch}#campaignPanel .campaign-actions{display:grid;gap:10px;margin:20px 0}#campaignPanel .campaign-actions button{text-align:left;padding:12px}#campaignPanel details{margin-top:25px}#campaignPanel .campaign-journal p{font-size:13px;line-height:1.7}@media(max-width:760px){#campaignPanel .campaign-layout{grid-template-columns:1fr}}';document.head.append(style);
 let lastDrawKey;function draw(){const rows=P.summaries(),selected=rows.find(q=>q.id===P.selected)||rows[0],arc=SpacePatriotCampaign.arcs.find(a=>a.id===selected.id),n=P.current(selected.id),drawKey=P.selected+JSON.stringify(rows.map(q=>[q.id,q.nodeId,q.status,q.progress]))+P.authority;if(drawKey===lastDrawKey)return;lastDrawKey=drawKey;panel.querySelector('nav').replaceChildren(...rows.map(row=>{const b=document.createElement('button');b.textContent=(row.id===selected.id?'◆ ':'')+row.title+' · '+(row.available===false?'locked':row.status);b.onclick=()=>{P.selected=row.id;draw();};return b;}));panel.querySelector('small').textContent=arc.speaker+' · '+(P.authority?'CAPTAIN’S CASE FILE':'SHARED CREW BRIEFING');panel.querySelector('h3').textContent=n?.title||arc.title;panel.querySelector('.campaign-text').textContent=n?.text||(n?.type==='objective'?n.title+'. '+({terminal:'Use a city computer with Z; a gas-world record is available from its orbital habitat.',sample:'Land, step outside and use the surface sampler with N.',delivery:'Buy the cargo through Markets, bring it to the named port, then hand it over here.',power:'Use the reactor controls in a city building. An operational reactor can be cycled off and back on.',combat:'Use Tactical to join a local encounter and defeat a hostile fighter or soldier.',station:'Follow the route to the orbital habitat.'}[n.location.kind]):n?.type==='end'?P.engine.state.journal.filter(j=>j.questId===arc.id).at(-1)?.text:arc.brief);
  const actions=panel.querySelector('.campaign-actions');actions.replaceChildren();const button=(text,fn,enabled=true)=>{const b=document.createElement('button');b.textContent=text;b.disabled=!enabled;b.onclick=()=>{fn();draw();};actions.append(b);};
  if(selected.status==='available')button(selected.available?'Take this case':'Complete: '+arc.requires.join(', '),()=>P.start(selected.id),P.authority&&selected.available);
  else if(selected.status==='active'&&n?.type==='dialogue')for(const c of P.engine.choices(selected.id))button(c.text,()=>P.choose(selected.id,c.id),P.authority&&c.enabled);
  else if(selected.status==='active'&&n?.location){button('Plot route · '+n.location.world,()=>{if(P.navigate(selected.id))BloxPause.dismiss();else A.toast(A.flight.message);});if(n.location.kind==='delivery')button('Hand over '+n.location.units+' '+n.location.good,()=>{if(!P.deliver(selected.id))A.toast('Reach the destination port with unreserved cargo.');},P.authority);if(n.location.kind==='terminal')button('Read orbital habitat record',()=>{if(!P.readStation(selected.id))A.toast('This record needs a gas-world orbital habitat; otherwise use a city computer.');},P.authority);}
  panel.querySelector('.campaign-journal').replaceChildren(...P.engine.state.journal.slice(-30).reverse().map(j=>{const p=document.createElement('p');p.textContent=j.text;return p;}));
 }
 window.CampaignUI={open(){draw();BloxPause.present('campaignPanel',true);},draw};
 const collect=A.flight.collect.bind(A.flight);A.flight.collect=(...args)=>{const ok=collect(...args);if(ok)P.signal('sample',A.flight.nearest().body.name);return ok;};
 const computer=window.openCityComputer;window.openCityComputer=(id)=>{const current=A.city.current;if(current&&id==='terminal')P.signal('terminal',current.city.body.name);return computer(id);};
 const operate=A.city.operate.bind(A.city);A.city.operate=(id,action)=>{const ok=operate(id,action);if(ok&&P.authority&&id==='reactor'){const cur=A.city.current,sim=C.CityWorld.machinery(cur.city,cur.building);if(sim.get('reactor').params.command)P.signal('power',cur.city.body.name);}return ok;};
 const hit=A.combat.applyHit.bind(A.combat);A.combat.applyHit=(h,...args)=>{const e=h.entity,before=e.hull;const out=hit(h,...args);if(P.authority&&before>0&&e.hull<=0&&!e.wildlife&&!e.civilian&&!e.local&&!e.remote)P.signal('combat',A.flight.nearest().body.name);return out;};
 const frame=PlanetEngineUI.update;let last=performance.now();PlanetEngineUI.update=()=>{frame();const now=performance.now();if(!A.isPaused())P.update(Math.min(.25,(now-last)/1000));last=now;if(!panel.hidden)draw();};draw();
})();
