(function(){function init(){if(!window.longway){addEventListener('longway-ready',init,{once:true});return;}
 const app=longway,C=LongwayCore,W=C.CityWorld;app.inventory=new C.FieldInventory(app);
 const button=document.createElement('button');button.id='introCity';button.className='large';button.textContent='Explore the space city ↗';document.querySelector('.intro-actions').prepend(button);
 button.onclick=()=>{const f=app.flight,b=app.world.system([0,0,0]).find(b=>b.name==='Earth')||app.world.system([0,0,0]).find(b=>b.type===1),city=W.forBody(b),build=city.buildings[6];f.place(b,'surface');f.walking=true;f.bridgeWalk=false;f.vehicle.state='onfoot';f.vehicle.transition=null;f.position=W.worldPoint(app.world,b,[build.x,W.BASE+W.EYE,build.z-15]);f.up=app.world.site(b).up.slice();f.forward=C.mul(app.world.site(b).forward,-1);f.viewPitch=f.viewYaw=0;f.velocity=[0,0,0];f.orthogonalize();app.city.update(0);app.start();app.focusScene();app.render();};
 const panel=document.createElement('aside');panel.id='cityPanel';panel.setAttribute('aria-label','City and elevator controls');panel.innerHTML='<small>SPACEPORT DISTRICT</small><strong></strong><p></p><div class="floors"></div><button id="cityInventory">Equipment & fabrication</button>';document.body.append(panel);
 const manifest=document.createElement('section');manifest.id='fieldInventory';manifest.hidden=true;manifest.innerHTML='<div class="heading"><strong>FIELD EQUIPMENT</strong><button id="closeInventory">Close ×</button></div><p>Supplies shared with weapon reloads and repairs.</p><div class="items"></div><div class="recipes"></div><p id="inventoryMessage"></p>';document.body.append(manifest);
 BloxUI.registerDialog('fieldInventory');const open=()=>{if(manifest.hidden)BloxUI.open('fieldInventory');else BloxUI.close();};panel.querySelector('#cityInventory').onclick=open;manifest.querySelector('#closeInventory').onclick=()=>BloxUI.close();
 const nav=document.createElement('button');nav.textContent='Equipment';nav.onclick=open;document.querySelector('.top-actions').append(nav);
 const style=document.createElement('style');style.textContent=`#cityPanel{position:fixed;right:28px;top:112px;z-index:12;width:242px;padding:18px;background:#061417ed;border:8px solid transparent;border-image:var(--hud-frame) 85 fill stretch;color:#d5e1d8;box-shadow:0 8px 30px #0004}#cityPanel[hidden],#fieldInventory[hidden]{display:none}#cityPanel small{letter-spacing:2px;font-size:9px;color:#9bb8ad}#cityPanel strong{display:block;font-size:15px;margin:10px 0}#cityPanel p{font-size:11px;line-height:1.7;white-space:pre-line}#cityPanel button{width:100%;margin-top:5px;font-size:10px}#cityPanel .floors{display:grid;grid-template-columns:1fr 1fr;gap:4px}#fieldInventory{position:fixed;z-index:60;left:50%;top:50%;transform:translate(-50%,-50%);width:min(540px,90vw);padding:24px;background:#081519f5;border:12px solid transparent;border-image:var(--hud-frame) 85 fill stretch;color:#c7d8d1}#fieldInventory .heading{display:flex;justify-content:space-between;align-items:center}#fieldInventory .items{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:18px 0}#fieldInventory .items div{padding:12px;background:#3a514733;border:1px solid #647b7144}#fieldInventory .items b{display:block;font-size:24px;margin-top:6px}#fieldInventory p{font-size:12px;line-height:1.7}#fieldInventory .recipes button{display:block;width:100%;margin:6px 0}`;document.head.append(style);
 addEventListener('keydown',e=>{if(e.code==='KeyZ'&&!e.repeat&&!app.isPaused()&&app.city.current&&(app.city.nearLift||app.city.nearMachine)&&!/INPUT|TEXTAREA/.test(e.target.tagName)){e.preventDefault();e.stopImmediatePropagation();app.city.interact();document.exitPointerLock?.();}},true);
 const terminal=document.createElement('section');terminal.id='cityTerminal';terminal.hidden=true;terminal.innerHTML='<h2>City operations computer</h2><p id="terminalLocation"></p><div id="cityMachineList"></div><button id="terminalMarket">Open local market</button><p>Power switches operate the MachineWorks network. Reactor power supplies the lift, ventilation, conveyor and pumps. Repairs cost 25 credits.</p>';document.body.append(terminal);
 window.openCityComputer=(id)=>{const cur=app.city.current;if(!cur)return;app.city.machineSelected=id;window.BloxPause?.present('cityTerminal',true);renderComputer();};
 document.getElementById('terminalMarket').onclick=()=>{document.getElementById('marketWorld').value=app.city.current.city.body.id;BloxPause.present('economyPanel',true);};
 function renderComputer(){if(terminal.hidden||!app.city.current)return;const {city,building:b}=app.city.current,sim=W.machinery(city,b);document.getElementById('terminalLocation').textContent=city.body.name+' / '+b.doc.name;document.getElementById('cityMachineList').replaceChildren(...[...sim.nodes.values()].map(n=>{const row=document.createElement('div'),label=document.createElement('span');row.className='market-row';row.dataset.machine=n.id;label.textContent=n.type.toUpperCase()+' · '+Math.round(n.state.power*100)+'% power · '+Math.round(n.state.health)+'% integrity';row.append(label);if(n.id!=='lift'){const b=document.createElement('button');b.textContent=n.params.command?'SWITCH OFF':'SWITCH ON';b.onclick=()=>{app.city.operate(n.id);renderComputer();};row.append(b);}const repair=document.createElement('button');repair.textContent='REPAIR · 25 cr';repair.disabled=n.state.health>=100;repair.onclick=()=>{app.city.operate(n.id,'repair');renderComputer();};row.append(repair);return row;}));}
 setInterval(renderComputer,700);
 const context=document.createElement('button');context.id='cityInteract';context.hidden=true;context.onclick=()=>{app.city.interact();document.exitPointerLock?.();};document.body.append(context);
 let revision=-1,lastLift='';
 const before=window.PlanetEngineUI.update;
 window.PlanetEngineUI.update=()=>{before();const S=app.city,cur=S.current;context.hidden=!cur||!S.prompt||app.isPaused();context.textContent=S.prompt;panel.hidden=!cur||!app.started;if(cur){const survey=document.querySelector('#fieldContract');if(!survey.closest('#pauseDeck'))survey.hidden=true;const b=cur.building,e=cur.city.elevators.get(b.id);panel.querySelector('strong').textContent=b.doc.name;panel.querySelector('p').textContent=`Floor ${(S.floor??0)+1} / ${b.levels} · ${S.room||'CONCOURSE'}\n${S.prompt||'Walk into furnished rooms and workspaces.'}\nLift · ${e.phase==='moving'?'moving to '+(e.target+1):'floor '+(e.floor+1)}`;
   const key=b.id+':'+S.panelOpen+':'+S.inLift+':'+e.phase+':'+e.floor;if(key!==lastLift){lastLift=key;const floors=panel.querySelector('.floors');floors.replaceChildren();if(S.panelOpen&&S.inLift)for(let k=0;k<b.levels;k++){const bt=document.createElement('button');bt.textContent=`0${k+1} ${b.doc.levels[k].name}`;bt.disabled=e.phase!=='open'||e.floor===k;bt.onclick=()=>{S.requestFloor(b,k);lastLift='';app.focusScene();};floors.append(bt);}}}
  const engine=app.inventory.engine;if(!manifest.hidden&&revision!==engine.state.revision){revision=engine.state.revision;const list=manifest.querySelector('.items');list.replaceChildren();for(const def of Object.values(engine.definitions)){const d=document.createElement('div'),name=document.createElement('span'),count=document.createElement('b');name.textContent=def.name;count.textContent=engine.count(def.id);d.append(name,count);list.append(d);}const recipes=manifest.querySelector('.recipes');recipes.replaceChildren();for(const recipe of Object.values(engine.recipes)){const bt=document.createElement('button');bt.textContent=recipe.name;bt.onclick=()=>{const result=app.inventory.craft(recipe.id);manifest.querySelector('#inventoryMessage').textContent=result.ok?'Fabrication complete.':result.error;revision=-1;};recipes.append(bt);}}
 };
}init();})();
