/* Bounded, host-owned background markets. Remote worlds produce, consume and
   exchange cargo even when their geometry and NPCs are not being rendered. */
(function initEconomy(){
 if(!window.longway)return addEventListener('longway-ready',initEconomy,{once:true});
 const A=longway,C=LongwayCore,F=A.flight,goods={ore:{name:'Refined ore',base:26},organics:{name:'Food & organics',base:34},crystal:{name:'Energy crystals',base:58}};
 class Economy{
  constructor(){this.time=0;this.accumulator=0;this.convoys=[];this.serial=0;this.ledger=[];this.factions={union:{treasury:60000,influence:34},helix:{treasury:80000,influence:36},redwake:{treasury:45000,influence:30}};this.markets=new Map(A.world.catalog.map((b,i)=>[b.id,{id:b.id,faction:['union','helix','redwake'][i%3],stock:Object.fromEntries(Object.keys(goods).map((g,k)=>[g,90+C.hash(b.seed+k)%130])),production:{ore:[0,2,5].includes(b.type)?.35:.08,organics:b.type===1?.42:.015,crystal:[3,4,5].includes(b.type)?.22:.045},demand:{ore:.11,organics:.10,crystal:.055},activity:0}]));this.accounts=new Map();this.owned=new Set([F.craft.id]);this.jobs=[];this.nextTrade=2;
   try{const save=JSON.parse(localStorage.getItem('space-patriot-economy-v1'));if(save?.version===1){if(Number.isFinite(save.credits)&&save.credits>=0)F.ship.credits=save.credits;for(const g of Object.keys(goods))if(Number.isInteger(save.cargo?.[g])&&save.cargo[g]>=0&&save.cargo[g]<=F.ship.capacity)F.ship.cargo[g]=save.cargo[g];if(Array.isArray(save.owned))for(const id of save.owned)if(C.CRAFTS.some(c=>c.id===id))this.owned.add(id);this.time=Number.isFinite(save.time)?Math.max(0,save.time):0;this.nextTrade=this.time+2;this.serial=Number.isInteger(save.serial)?Math.max(0,save.serial):Math.floor(this.time/5);this.jobs=(save.jobs||[]).filter(j=>typeof j.id==='string'&&A.world.byId(j.from)&&A.world.byId(j.to)&&goods[j.good]&&j.units===4&&Number.isFinite(j.reward)&&['in transit','delivered'].includes(j.status)).slice(0,60);if(F.cargoCount()>F.ship.capacity)F.ship.cargo={ore:0,organics:0,crystal:0};for(const m of save.markets||[]){const to=this.markets.get(m.id);if(to&&Object.values(m.stock||{}).length===3&&Object.values(m.stock).every(v=>Number.isFinite(v)&&v>=0&&v<=2000))to.stock={...m.stock};}}}catch{}
   const contacts=A.combat.contacts.bind(A.combat);A.combat.contacts=()=>[...contacts(),...this.traffic()];
   A.world.market=b=>Object.fromEntries(Object.keys(goods).map(g=>[g,this.price(b.id,g,'sell')]));
   const service=F.service.bind(F);F.service=(action,resource)=>{if(['buy','sell'].includes(action))return this.trade(F.docked?.body.id,resource,action,1);return service(action,resource);};
   const select=F.selectCraft.bind(F);F.selectCraft=id=>{if(this.owned.has(id))return select(id);const cost=this.shipPrice(id);if(!cost||F.ship.credits<cost){F.message='SHIP PURCHASE · '+cost+' credits required';return false;}const ok=select(id);if(ok){F.ship.credits-=cost;this.owned.add(id);this.record('Purchased '+F.craft.name,-cost);this.save();}return ok;};
   const update=F.update.bind(F);F.update=(dt,input={})=>{update(dt,input);this.update(dt);};
   const serviceCombat=A.combat.service.bind(A.combat);A.combat.service=()=>{const cost=this.serviceCost();if(F.ship.credits<cost){A.combat.message='SERVICE · '+cost+' credits required';return false;}const ok=serviceCombat();if(ok&&cost){F.ship.credits-=cost;this.record('Rearm & repair',-cost);}return ok;};
  }
  traffic(){return this.convoys.map(v=>{const a=A.world.station(A.world.byId(v.from)),b=A.world.station(A.world.byId(v.to)),t=C.clamp((this.time-v.depart)/(v.arrive-v.depart),0,1),position=C.mix(a.center,b.center,t),forward=C.unit(C.sub(b.center,a.center));return{id:v.id,name:v.faction.toUpperCase()+' CARGO / '+goods[v.good].name,kind:'ally',craftId:C.CRAFTS.find(c=>c.className==='Exploration corvette').id,position,forward,up:a.up,velocity:C.mul(forward,.2),hull:100,radius:.03};}).filter(v=>C.length(C.sub(v.position,F.position))<30).slice(0,8);}
  shipPrice(id){const c=C.CRAFTS.find(c=>c.id===id);return c?Math.round(c.dimensions[0]*8):0;}
  serviceCost(){const B=A.combat;return Math.ceil((100-F.ship.hull)*2+Object.entries(B.ammo).reduce((sum,[k,v])=>sum+Math.max(0,C.WEAPONS[k].mag-v.mag)*(k==='missile'?18:.08),0));}
  record(text,amount=0){this.ledger.unshift({time:this.time,text,amount});this.ledger=this.ledger.slice(0,20);}
  price(id,g,side='buy'){const m=this.markets.get(id);if(!m||!goods[g])return 0;const scarcity=C.clamp(180/Math.max(40,m.stock[g]),.55,3),owner=this.factions[m.faction],war=1+(100-owner.influence)*.001;return Math.max(1,Math.round(goods[g].base*scarcity*war*(side==='buy'?1.12:.9)));}
  inPort(id,position=F.renderPose().position){const b=A.world.byId(id);if(!b)return false;return C.length(C.sub(position,A.world.site(b).center))<.45||C.length(C.sub(position,A.world.station(b).center))<.6;}
  account(id){if(id===A.network?.peer?.id||id==='local')return{credits:F.ship.credits,cargo:F.ship.cargo,capacity:F.ship.capacity};if(!this.accounts.has(id))this.accounts.set(id,{credits:1200,cargo:{ore:0,organics:0,crystal:0},capacity:24});return this.accounts.get(id);}
  trade(id,g,side,quantity=1,peerId=null){if(!goods[g]||!['buy','sell'].includes(side)||!Number.isInteger(quantity)||quantity<1||quantity>24||!id)return false;if(!peerId&&A.network.role==='guest'){A.network.send({type:'economy',action:'trade',bodyId:id,good:g,side,quantity});return true;}
   const player=peerId?A.network.players.get(peerId):null;if(peerId&&!player)return false;if(!this.inPort(id,player?.position||F.renderPose().position)){F.message='Trade requires docking or a city terminal';return false;}const m=this.markets.get(id),account=this.account(peerId||'local'),cost=this.price(id,g,side)*quantity;if(side==='buy'){if(m.stock[g]<quantity||account.credits<cost||Object.values(account.cargo).reduce((a,b)=>a+b,0)+quantity>account.capacity){F.message='Insufficient credits, cargo space or market stock';return false;}account.credits-=cost;account.cargo[g]+=quantity;m.stock[g]-=quantity;}else{const reserved=peerId?0:this.jobs.filter(j=>j.status==='in transit'&&j.good===g).reduce((n,j)=>n+j.units,0);if(account.cargo[g]-reserved<quantity){F.message='Delivery cargo is sealed for its destination';return false;}account.credits+=cost;account.cargo[g]-=quantity;m.stock[g]+=quantity;}if(!peerId)F.ship.credits=account.credits;this.record((side==='buy'?'Bought ':'Sold ')+quantity+' '+goods[g].name,side==='buy'?-cost:cost);m.activity++;this.save();return true;}
  contracts(){const b=F.nearest().body,origin=this.markets.get(b.id),dest=A.world.catalog.filter(x=>x.id!==b.id&&x.systemIndex===b.systemIndex);return dest.slice(0,3).map((d,i)=>({id:b.id+':'+d.id,from:b.id,to:d.id,good:Object.keys(goods)[i%3],units:4,reward:240+i*120,status:'available'}));}
  acceptJob(id){if(this.jobs.some(j=>j.id===id))return false;const j=this.contracts().find(j=>j.id===id);if(!j||!this.inPort(j.from)||F.cargoCount()+j.units>F.ship.capacity||this.markets.get(j.from).stock[j.good]<j.units)return false;if(A.network.role==='guest'){F.message='Shared crew contracts are accepted by the host';return false;}F.ship.cargo[j.good]+=j.units;this.markets.get(j.from).stock[j.good]=Math.max(0,this.markets.get(j.from).stock[j.good]-j.units);this.jobs.push({...j,status:'in transit'});this.record('Cargo loaded for '+A.world.byId(j.to).name);this.save();return true;}
  deliverJob(id){const j=this.jobs.find(j=>j.id===id&&j.status==='in transit');if(!j||!this.inPort(j.to)||F.ship.cargo[j.good]<j.units)return false;F.ship.cargo[j.good]-=j.units;this.markets.get(j.to).stock[j.good]+=j.units;F.ship.credits+=j.reward;j.status='delivered';this.record('Delivery complete',j.reward);this.save();return true;}
  launchTrade(){const worlds=A.world.catalog,from=worlds[this.serial%worlds.length],siblings=worlds.filter(b=>b.systemIndex===from.systemIndex&&b.id!==from.id),to=siblings[(this.serial+1)%siblings.length]||worlds[(this.serial+7)%worlds.length],g=Object.keys(goods)[this.serial%3],m=this.markets.get(from.id),faction=this.factions[m.faction],units=Math.min(14,Math.floor(m.stock[g]/5)),cost=units*this.price(from.id,g,'sell');if(units>0&&faction.treasury>=cost){m.stock[g]-=units;faction.treasury-=cost;this.convoys.push({id:'trade-'+this.serial,from:from.id,to:to.id,good:g,units,faction:m.faction,depart:this.time,arrive:this.time+65+this.serial%7*18});}this.serial++;}
  update(dt){if(A.network.role==='guest')return;this.accumulator+=Math.min(dt,.1);if(this.accumulator<.5)return;const step=this.accumulator;this.accumulator=0;this.time+=step;for(const m of this.markets.values())for(const g of Object.keys(goods))m.stock[g]=C.clamp(m.stock[g]+(m.production[g]-m.demand[g])*step,5,600);
   if(this.time>=this.nextTrade){this.nextTrade=this.time+5;if(this.convoys.length<60)this.launchTrade();}
   for(const v of this.convoys)if(v.arrive<=this.time&&!v.delivered){v.delivered=true;const m=this.markets.get(v.to),f=this.factions[v.faction];m.stock[v.good]+=v.units;f.treasury+=v.units*this.price(v.to,v.good,'buy');f.influence=C.clamp(f.influence+.08,10,80);m.activity++;this.record(v.faction+' convoy arrived at '+A.world.byId(v.to).name);}
   this.convoys=this.convoys.filter(v=>!v.delivered);if(Math.floor(this.time/30)>Math.floor((this.time-step)/30)){for(const [id,f]of Object.entries(this.factions)){const spend=Math.min(f.treasury,140+Math.round(f.influence*3));f.treasury-=spend;f.influence=C.clamp(f.influence+(spend>200?.12:-.15),10,80);}this.save();}
  }
  snapshot(){return{time:this.time,markets:[...this.markets.values()].map(m=>({id:m.id,stock:m.stock,activity:m.activity,faction:m.faction})),convoys:this.convoys,factions:this.factions,accounts:[...this.accounts].map(([id,a])=>({id,...a}))};}
  acceptSnapshot(s){if(!s||!Number.isFinite(s.time)||!Array.isArray(s.markets)||s.markets.length>20)return;this.time=s.time;for(const row of s.markets){const m=this.markets.get(row.id);if(m&&Object.keys(goods).every(g=>Number.isFinite(row.stock?.[g])&&row.stock[g]>=0&&row.stock[g]<=2000))Object.assign(m,row);}if(Array.isArray(s.convoys)&&s.convoys.length<=60)this.convoys=s.convoys.filter(v=>A.world.byId(v.from)&&A.world.byId(v.to)&&goods[v.good]&&Number.isFinite(v.depart)&&Number.isFinite(v.arrive));for(const id of Object.keys(this.factions))if(Number.isFinite(s.factions?.[id]?.treasury)&&Number.isFinite(s.factions[id].influence)&&s.factions[id].influence>=0&&s.factions[id].influence<=100)this.factions[id]={...s.factions[id]};const account=s.accounts?.find(x=>x.id===A.network.peer?.id);if(account&&Number.isFinite(account.credits)&&Object.keys(goods).every(g=>Number.isInteger(account.cargo?.[g])&&account.cargo[g]>=0)){F.ship.credits=account.credits;F.ship.cargo={...account.cargo};}}
  save(){if(A.network.role==='guest')return;try{localStorage.setItem('space-patriot-economy-v1',JSON.stringify({version:1,time:this.time,serial:this.serial,jobs:this.jobs,credits:F.ship.credits,cargo:F.ship.cargo,owned:[...this.owned],markets:[...this.markets.values()].map(m=>({id:m.id,stock:m.stock}))}));}catch{F.message='Browser storage unavailable · Progress is retained for this session';}}
 }
 A.economy=new Economy();
 const p=document.createElement('section');p.id='economyPanel';p.hidden=true;p.innerHTML='<h2>Markets & contracts</h2><p id="walletLine"></p><select id="marketWorld"></select><div id="marketGoods"></div><h3>Delivery board</h3><div id="deliveryJobs"></div><h3>Live interplanetary traffic</h3><div id="tradeTraffic"></div><h3>Faction economies</h3><div id="factionBalances"></div><p>Worlds produce and consume goods continuously. Convoys move stock and factions pay for their operations. Crew markets are simulated by the host.</p>';document.body.append(p);for(const b of A.world.catalog){const o=document.createElement('option');o.value=b.id;o.textContent=b.system+' / '+b.name;p.querySelector('select').append(o);}p.querySelector('select').value=F.nearest().body.id;
 let key='';function render(){if(p.hidden)return;const E=A.economy,id=p.querySelector('select').value,m=E.markets.get(id);document.getElementById('walletLine').textContent=Math.floor(F.ship.credits).toLocaleString()+' credits · Cargo '+F.cargoCount()+' / '+F.ship.capacity+' · '+(E.inPort(id)?'PORT ACCESS':'REMOTE PRICE VIEW');const k=id+Math.floor(E.time/2)+JSON.stringify(F.ship.cargo)+Math.floor(F.ship.credits);if(k!==key){key=k;document.getElementById('marketGoods').replaceChildren(...Object.entries(goods).map(([g,def])=>{const row=document.createElement('div');row.className='market-row';const label=document.createElement('span');label.textContent=def.name+' · stock '+Math.floor(m.stock[g])+' · aboard '+F.ship.cargo[g];row.append(label);for(const side of ['buy','sell']){const b=document.createElement('button');b.textContent=side.toUpperCase()+' '+E.price(id,g,side)+' cr';b.disabled=!E.inPort(id);b.onclick=()=>{E.trade(id,g,side);key='';render();};row.append(b);}return row;}));document.getElementById('deliveryJobs').replaceChildren(...[...E.jobs.filter(x=>x.status!=='delivered'),...E.contracts().filter(x=>!E.jobs.some(j=>j.id===x.id))].map(j=>{const b=document.createElement('button');b.textContent=(j.status==='available'?'ACCEPT: ':'DELIVER: ')+j.units+' '+goods[j.good].name+' → '+A.world.byId(j.to).name+' · '+j.reward+' cr';b.onclick=()=>{const ok=j.status==='available'?E.acceptJob(j.id):E.deliverJob(j.id);A.toast(ok?'Contract updated':'Visit the departure/destination port with room for the cargo');key='';render();};return b;}));document.getElementById('tradeTraffic').textContent=E.convoys.slice(-8).map(v=>A.world.byId(v.from).name+' → '+A.world.byId(v.to).name+' / '+v.units+' '+v.good+' / '+Math.ceil(v.arrive-E.time)+' s').join('\n')||'Trade dispatch is preparing the next convoy.';document.getElementById('factionBalances').textContent=Object.entries(E.factions).map(([id,f])=>id.toUpperCase()+' · '+Math.round(f.treasury).toLocaleString()+' cr · influence '+f.influence.toFixed(1)).join('\n');}}
 setInterval(render,500);p.querySelector('select').onchange=()=>{key='';render();};
})();
