/* Each cockpit display owns a page and click regions; it never opens a modal. */
(function(){const states=Array.from({length:3},()=>({page:null,offset:0,hits:[],mode:'worlds'}));
 const names={campaignPanel:'THE LONG DEBT',navigation:'NAVIGATION',radarPanel:'TACTICAL',weaponsPanel:'FIRE CONTROL',engineeringDialog:'ENGINEERING',crewPanel:'CREW LINK',shipboardPanel:'SHIP STATIONS'};
 const api=window.BloxMFD={states,revision:0,invalidate(){this.revision++;const A=window.longway;if(!A)return;A.combat.trigger=false;A.renderer.needsRender=true;if(A.visuals)A.visuals.instrumentTime=-Infinity;window.BloxArtwork?.update();},select(index,page){if(!states[index]||!names[page]||!window.longway)return;Object.assign(states[index],{page,offset:0,mode:'worlds',engineeringMode:'overview',hits:[]});const A=longway;A.flight.drive.instruments=!(A.flight.walking||A.flight.bridgeWalk);document.exitPointerLock?.();this.invalidate();},click(index,event){const s=states[index];if(!s||!window.longway)return;if(!s.page)return api.select(index,['navigation','radarPanel','engineeringDialog'][index]);const x=event.offsetX,y=event.offsetY,hit=s.hits.find(h=>x>=h.x&&x<=h.x+h.w&&y>=h.y&&y<=h.y+h.h);if(hit){hit.action();this.invalidate();}},draw(index,canvas){const s=states[index];if(!s?.page||!window.longway)return false;const A=longway,F=A.flight,B=A.combat,S=A.systems,C=LongwayCore,q=canvas.getContext('2d');s.hits=[];q.fillStyle='#051214';q.fillRect(0,0,640,380);q.strokeStyle='#3b645f';q.strokeRect(12,12,616,356);
  const text=(v,x,y,size=24,color='#c2d9ca')=>{q.fillStyle=color;q.font=size+'px monospace';q.textAlign='left';q.fillText(String(v),x,y,580);};
  const button=(label,x,y,w,h,action)=>{q.fillStyle='#17332f';q.fillRect(x,y,w,h);q.strokeStyle='#41645a';q.strokeRect(x,y,w,h);text(label,x+10,y+h*.7,22);s.hits.push({label,x,y,w,h,action});};
  text(names[s.page],24,41,25);button('STATUS',492,20,122,31,()=>s.page=null);let row=0;
  const line=(label,action)=>{const y=65+row++*40;if(action)button(label,24,y,590,35,action);else text(label,32,y+25,23);};
  if(s.page==='campaignPanel'){
   const P=A.campaign,rows=P.summaries();if(!s.quest){for(const row of rows.slice(s.offset,s.offset+5))line(row.title,()=>{s.quest=row.id;s.textPage=0;});button('NEXT CASES',24,281,270,35,()=>s.offset=(s.offset+5)%rows.length);}
   else{const state=rows.find(r=>r.id===s.quest),n=P.current(s.quest);if(state.status==='available'){line(state.title);line(state.available?'TAKE THIS CASE':'CASE LOCKED',state.available?()=>P.start(s.quest):null);}else if(n?.type==='dialogue'){const words=n.text.split(' '),lines=[];let lineText='';for(const word of words){if((lineText+' '+word).length>47){lines.push(lineText);lineText='';}lineText+=(lineText?' ':'')+word;}if(lineText)lines.push(lineText);const offset=(s.textPage||0)*3;for(const t of lines.slice(offset,offset+3))line(t);if(offset+3<lines.length)line('READ ON',()=>s.textPage=(s.textPage||0)+1);else for(const c of n.choices.slice(0,2))line(c.text,()=>{if(P.authority)P.choose(s.quest,c.id);s.textPage=0;});}else if(n?.location){line(n.location.world+' / '+n.location.kind.toUpperCase());line('PLOT ROUTE',()=>P.navigate(s.quest));if(n.location.kind==='delivery')line('DELIVER '+n.location.units+' '+n.location.good,()=>P.deliver(s.quest));if(n.location.kind==='terminal')line('READ ORBITAL RECORD',()=>P.readStation(s.quest));line(n.title);}else line('CASE CLOSED · JOURNAL SAVED');button('CASE LIST',24,281,270,35,()=>s.quest=null);}
  }else if(s.page==='navigation'){
   const body=A.world.byId(s.bodyId)||F.nearest().body,places=A.outposts?.list(body)||[];
   if(s.mode==='worlds'){const list=A.world.catalog;for(const b of list.slice(s.offset,s.offset+5))line(b.name+' / '+b.system,()=>{s.bodyId=b.id;s.mode='destination';s.offset=0;});button('NEXT WORLDS',24,281,265,35,()=>s.offset=(s.offset+5)%list.length);button('STORY CASES',310,281,304,35,()=>{s.page='campaignPanel';s.quest=null;s.offset=0;});}
   else if(s.mode==='destination'){line(body.name.toUpperCase());line('ORBITAL APPROACH',()=>{F.walking=false;F.transfer(body,true);});line('LAND AT PRIMARY SPACEPORT',()=>A.outposts.route(body.id+':city:0'));line('CITIES & OUTPOSTS ('+places.length+')',()=>{s.mode='places';s.offset=0;});line('WORLD LIST',()=>s.mode='worlds');}
   else{for(const r of places.slice(s.offset,s.offset+5))line((r.kind==='city'?'CITY  ':'POST  ')+r.name,()=>{A.outposts.select(r.id);s.destination=r.id;s.mode='approach';});button('NEXT SITES',24,281,265,35,()=>s.offset=(s.offset+5)%places.length);button('BACK',310,281,304,35,()=>s.mode='destination');}
   if(s.mode==='approach'){q.fillStyle='#051214';q.fillRect(18,57,608,272);s.hits=s.hits.filter(h=>h.y<57);row=0;line(A.outposts.records.get(s.destination)?.name);line('ENGAGE LANDING APPROACH',()=>{A.outposts.route(s.destination);s.mode='destination';});line('BACK TO SITES',()=>s.mode='places');}
  }else if(s.page==='radarPanel'){line(B.enemies.filter(e=>e.hull>0).length+' CONTACTS / '+(B.radarRange*1000).toFixed(0)+' m');for(const e of B.enemies.filter(e=>e.hull>0).slice(s.offset,s.offset+4))line((B.targetId===e.id?'◆ ':'◇ ')+e.name,()=>{B.targetId=e.id;});button('CYCLE CONTACT',24,281,285,35,()=>B.cycleTarget());button('RANGE',330,281,284,35,()=>B.radarRange=B.radarRange>=10?.35:B.radarRange*2);
  }else if(s.page==='weaponsPanel'){line((B.armed?'ARMED':'SAFE')+' / '+B.spec.name,()=>B.setArmed(!B.armed));for(const key of ['laser','kinetic','missile'])line((B.key===key?'◆ ':'◇ ')+C.WEAPONS[key].name+'  '+(key==='laser'?Math.round(B.capacitor)+'%':B.ammo[key].mag+' / '+B.ammo[key].reserve),()=>{B.selectWeapon(key);B.setArmed(true);});line('RELOAD',()=>B.reload());line(B.fireStatus);
  }else if(s.page==='engineeringDialog'){
   if(!s.engineeringMode||s.engineeringMode==='overview'){line('POWER '+(F.drive.power?'ON':'OFF')+' · MODE '+S.mode,()=>F.togglePower());line('FLIGHT MODE / '+S.mode,()=>S.setMode(S.mode==='SCM'?'NAV':'SCM'));line('POWER ALLOCATION',()=>s.engineeringMode='power');line('COMPONENTS & REPAIR',()=>{s.engineeringMode='components';s.offset=0;});line('BALANCED POWER',()=>S.preset('BALANCED'));}
   else if(s.engineeringMode==='power'){for(const key of ['engines','weapons','shields']){const y=72+row++*55;button('- '+key.toUpperCase(),24,y,285,42,()=>S.allocate(key,-1));button(key.toUpperCase()+' '+S.allocations[key]+' +',322,y,292,42,()=>S.allocate(key,1));}button('BACK',24,281,270,35,()=>s.engineeringMode='overview');button('BALANCED',310,281,304,35,()=>S.preset('BALANCED'));}
   else if(s.engineeringMode==='components'){for(const [key,c]of Object.entries(S.components).slice(s.offset,s.offset+5))line(key.toUpperCase()+' / '+Math.round(c.health)+'%',()=>{s.component=key;s.engineeringMode='component';});button('MORE',24,281,270,35,()=>s.offset=(s.offset+5)%Object.keys(S.components).length);button('BACK',310,281,304,35,()=>s.engineeringMode='overview');}
   else{const c=S.components[s.component];line(s.component.toUpperCase()+' / '+Math.round(c.health)+'% INTEGRITY');line('TEMPERATURE '+Math.round(c.temperature)+' · SPARES '+Math.floor(S.spares));line(c.enabled?'ISOLATE COMPONENT':'ENABLE COMPONENT',()=>S.toggleComponent(s.component));line('FIELD REPAIR',()=>{S.repair(s.component);});line(c.enabled?'ISOLATE BEFORE REPAIR':S.repairing===s.component?'REPAIR IN PROGRESS':'COMPONENT ISOLATED');button('BACK',24,281,270,35,()=>s.engineeringMode='components');}
  }else if(s.page==='shipboardPanel'){line('PILOT / '+F.craft.name);line('LEAVE PILOT SEAT',()=>{if(F.craft.dimensions[0]>60)S.tourBridge(true);else F.toggleWalk();});line('LANDING GEAR '+Math.round(F.vehicle.gear*100)+'%',()=>F.toggleGear());line('HANGAR / RAISE SHIP',()=>A.shipboard.launchLift());line('LAND / TAKE OFF',()=>F.toggleLanding());line('EXTERIOR / COCKPIT CAMERA',()=>F.toggleCamera());
  }else if(s.page==='crewPanel'){line('LINK '+A.network.status+' / '+(A.network.room||'OFFLINE'));line('HOST CREW ROOM',()=>A.network.host());for(const [id,v]of [...A.shipboard.vessels()].filter(([id])=>id!==A.shipboard.id).slice(0,3))line('BOARD '+(C.CRAFTS.find(c=>c.id===v.craftId)?.name||id),()=>A.shipboard.board(id));line('CREW ABOARD '+A.shipboard.occupants.size);}
  text('LIVE SHIP SYSTEMS · Z CURSOR · TAB TERMINAL',25,354,18,'#739a8e');return true;
 }};
})();
