(function initShipboard(){
 if(!window.longway)return addEventListener('longway-ready',initShipboard,{once:true});
 const A=longway,C=LongwayCore,F=A.flight,S=A.systems,B=A.combat;
 class Shipboard{
  constructor(){this.requestSerial=0;this.pending=null;this.aboard=null;this.occupants=new Map();this.home=null;this.lift=null;this.encounters=new Map();this.active=null;this.elapsed=0;
   try{const h=JSON.parse(localStorage.getItem('space-patriot-home-v1'));if(A.world.byId(h?.bodyId))this.home=h;}catch{}
   const field=A.world.cityField.bind(A.world);A.world.cityField=(q,body)=>{let d=field(q,body);if(body.id!==this.home?.bodyId||body.activeSettlement&&!body.activeSettlement.primary)return d;const p=[q[0]*1000+165,q[1]*1000,-q[2]*1000],W=C.CityWorld,raised=(this.hangarRaised||0)*1000;const boxes=[...W.hangarWalls,{center:[0,raised,0],size:[136,1,235]}];for(const side of [-1,1])boxes.push({center:[side*(36+Math.min(1,raised/8)*78),36,0],size:[72,2,248]});for(const box of boxes)d=Math.min(d,W.distance(p,box)/1000);return d;};
   for(const operation of ['setMode','allocate','preset','toggleComponent','repair']){const run=S[operation].bind(S);S[operation]=(...args)=>{if(this.aboard&&!this.applyingSystems){if(S.seated!=='engineering')return false;const packet={action:'systems',operation,args,vesselId:this.aboard};if(A.network.role==='host')return this.acceptRequest(this.id,packet);A.network.send({type:'shipboard',...packet});return true;}return run(...args);};}
   const update=F.update.bind(F);F.update=(dt,input={})=>{this.update(dt);update(dt,this.lift?{}:input);if(this.lift)this.updateLift(dt);};
   const pose=F.renderPose.bind(F);F.renderPose=()=>{const p=pose();if(S.seated?.startsWith('turret')){p.position=this.turretOrigin();p.shipView=0;}return p;};
   const origin=B.origin.bind(B);B.origin=()=>S.seated?.startsWith('turret')?this.turretOrigin():origin();
  }
  systemState(){return structuredClone({mode:S.mode,allocations:S.allocations,components:S.components,spares:S.spares,pressure:S.pressure,profile:S.profile,repairing:S.repairing});}
  readSystems(v){if(!v||!['SCM','NAV'].includes(v.mode)||!['engines','weapons','shields'].every(k=>Number.isInteger(v.allocations?.[k])&&v.allocations[k]>=0&&v.allocations[k]<=12)||Object.values(v.allocations).reduce((a,b)=>a+b,0)!==12||!Object.keys(S.components).every(k=>Number.isFinite(v.components?.[k]?.health)&&v.components[k].health>=0&&v.components[k].health<=100&&Number.isFinite(v.components[k].temperature)&&typeof v.components[k].enabled==='boolean')||!Number.isFinite(v.spares)||!Number.isFinite(v.pressure))return false;for(const key of ['mode','allocations','components','spares','pressure','profile','repairing'])S[key]=structuredClone(v[key]);return true;}
  applySystems(packet){const {operation,args}=packet;if(this.aboard||!['setMode','allocate','preset','toggleComponent','repair'].includes(operation)||!Array.isArray(args)||args.length>2||!args.every(x=>typeof x==='string'&&x.length<30||Number.isInteger(x)&&Math.abs(x)<=1))return false;this.applyingSystems=true;try{return S[operation](...args);}finally{this.applyingSystems=false;}}
  request(action,extra={}){if(this.pending){F.message='Waiting for the ship station to confirm';return false;}const requestId=++this.requestSerial;this.pending={requestId,action};A.network.send({type:'state',state:A.network.state()});A.network.send({type:'shipboard',action,requestId,...extra});return true;}
  acceptResult(p){if(!this.pending||p.requestId!==this.pending.requestId)return;this.pending=null;this.acceptSnapshot(p.shipboard);if(!p.ok){F.message='Station request declined · Move closer or choose an available station';A.toast(F.message);}}
  get id(){return A.network?.peer?.id||'local';}
  vessel(){const v=this.own?.vehicle||F.vehicle;return{position:v.position.slice(),forward:v.forward.slice(),up:v.up.slice(),craftId:v.craftId,velocity:(this.own?.velocity||F.velocity).slice(),state:v.state,systems:this.own?.systems||this.systemState(),thrust:v.thrust||0,gear:v.gear||0,hull:F.ship.hull};}
  vessels(){const out=new Map([[this.id,this.vessel()]]);for(const e of B.remotes.values())if(e.vessel)out.set(e.id,e.vessel);return out;}
  board(vesselId){if(this.aboard||F.vehicle.transition)return false;const v=this.vessels().get(vesselId);if(!v||!(C.CRAFTS.find(c=>c.id===v.craftId)?.dimensions[0]>60)||C.length(C.sub(F.renderPose().position,v.position))>.15){F.message='Move within 150 m of a crew ship to request boarding';return false;}if(vesselId===this.id)return S.tourBridge(true);if(A.network.role==='host')return this.acceptRequest(this.id,{action:'board',vesselId});this.request('board',{vesselId});F.message='BOARDING REQUEST SENT';return true;}
  enterRemote(vesselId){if(this.aboard===vesselId)return;const v=this.vessels().get(vesselId);if(!v)return;if(!this.own)this.own={vehicle:F.vehicle,position:F.position.slice(),forward:F.forward.slice(),up:F.up.slice(),velocity:F.velocity.slice(),walking:F.walking,systems:this.systemState()};this.aboard=vesselId;F.vehicle={...F.vehicle,...structuredClone(v),transition:null};F.walking=false;S.remoteVessel=vesselId;S.tourBridge(true);S.bridgePosition=[0,0,4];this.attachPose(v);A.toast('BOARDED · '+(C.CRAFTS.find(c=>c.id===v.craftId)?.name||'Crew vessel'));}
  attachPose(v){Object.assign(F.vehicle,structuredClone(v));F.position=v.position.slice();F.forward=v.forward.slice();F.up=v.up.slice();F.velocity=v.velocity.slice();F.orthogonalize();this.readSystems(v.systems);}
  leaveRemote(reason='Returned to your vessel'){if(!this.own)return;const saved=this.own;this.readSystems(saved.systems);delete saved.systems;this.own=null;this.aboard=null;S.remoteVessel=null;S.tourBridge(false);Object.assign(F,saved);F.orthogonalize();B.trigger=B.armed=false;F.message=reason;}
  disembark(){if(!this.aboard)return false;if(!['landed','docked','onfoot'].includes(F.vehicle.state)){F.message='AIRLOCK INTERLOCK · The pilot must land or dock';return false;}const pose=F.renderPose(),v={...F.vehicle};this.release();this.leaveRemote('DISEMBARKED');F.position=C.add(v.position,C.mul(C.unit(C.cross(v.forward,v.up)),C.CRAFTS.find(c=>c.id===v.craftId).dimensions[1]*.0006+.008));const support=F.supportAt(F.position);if(support)F.position=C.add(support.point,C.mul(support.up,.00175));F.up=v.up;F.forward=pose.forward;F.walking=true;F.vehicle.state='onfoot';F.orthogonalize();return true;}
  release(){if(A.network.role==='host')this.occupants.delete(this.id);else if(A.network.links.size)this.request('leave');}
  sit(id){const station=S.interiorPlan?.stations.find(s=>s.id===id);if(!station||!F.bridgeWalk)return false;if(Math.hypot(S.bridgePosition[0]-station.x,S.bridgePosition[2]-station.z)>1.8){F.message='Walk up to the station and press Z';return false;}if(id==='pilot'){if(this.aboard){F.message='PILOT SEAT RESERVED · Your friend has the helm';return false;}this.stand();S.tourBridge(false);return true;}
   if(A.network.links.size){if(A.network.role==='host')return this.acceptRequest(this.id,{action:'seat',vesselId:this.aboard||this.id,seat:id});return this.request('seat',{vesselId:this.aboard||this.id,seat:id});}this.applySeat(id);return true;}
  applySeat(id){S.seated=id;F.drive.instruments=false;const st=S.interiorPlan?.stations.find(s=>s.id===id);if(st)S.bridgePosition=[st.x,0,st.z];F.viewYaw=F.viewPitch=0;B.armed=id.startsWith('turret');B.trigger=false;if(B.armed){B.selectWeapon('laser');A.systems.setMode('SCM');}F.message=id.startsWith('turret')?'REMOTE TURRET · Mouse aim · Click fire · Z stand':'ENGINEERING STATION · Z stand';if(id==='engineering')BloxMFD?.select(2,'engineeringDialog');}
  stand(notify=true){if(!S.seated)return;const station=S.interiorPlan?.stations.find(s=>s.id===S.seated);if(station)S.bridgePosition=[station.x-Math.sign(station.x)*1.4,0,station.z+1.1];S.seated=null;F.drive.instruments=false;F.message='STATION RELEASED · WASD to walk';document.getElementById('scene').focus({preventScroll:true});B.trigger=B.armed=false;if(A.network.role==='host'){const state=this.occupants.get(this.id);if(state)state.seat=null;}else if(notify&&A.network.links.size)this.request('stand');}
  turretOrigin(v=F.vehicle){const craft=C.CRAFTS.find(c=>c.id===v.craftId)||F.craft;return C.add(v.position,C.mul(v.up,craft.dimensions[2]*.0007+.002));}
  acceptRequest(id,p){const player=id===this.id?A.network.state():A.network.players.get(id);if(!player)return false;const owner=p.vesselId||this.occupants.get(id)?.vesselId,ve=owner===this.id?this.vessel():A.network.players.get(owner)?.vessel;
   if(p.action==='systems'){const row=this.occupants.get(id);if(row?.seat!=='engineering'||row.vesselId!==p.vesselId)return false;if(row.vesselId===this.id)return this.applySystems(p);const link=A.network.links.get(row.vesselId);if(!link)return false;A.network.transmit(link,{type:'vessel-systems',operation:p.operation,args:p.args});return true;}
   if(p.action==='leave'){this.occupants.delete(id);return true;}if(p.action==='stand'){const row=this.occupants.get(id);if(row)row.seat=null;return true;}
   if(!ve||!(C.CRAFTS.find(c=>c.id===ve.craftId)?.dimensions[0]>60))return false;
   if(p.action==='board'){if(C.length(C.sub(player.position,ve.position))>.15||id===owner)return false;this.occupants.set(id,{vesselId:owner,seat:null});if(id===this.id)this.enterRemote(owner);return true;}
   if(p.action==='seat'){if(id!==owner&&this.occupants.get(id)?.vesselId!==owner)return false;if(!['turret-dorsal','engineering'].includes(p.seat))return false;const local=player.interior?.position,station=C.InteriorLayout(C.CRAFTS.find(c=>c.id===ve.craftId)).stations.find(s=>s.id===p.seat);if(!local||Math.hypot(local[0]-station.x,local[2]-station.z)>1.8)return false;for(const [who,row]of this.occupants)if(who!==id&&row.vesselId===owner&&row.seat===p.seat)return false;this.occupants.set(id,{vesselId:owner,seat:p.seat});if(id===this.id)this.applySeat(p.seat);return true;}return false;
  }
  snapshot(){return{occupants:[...this.occupants].map(([id,v])=>({id,...v})),active:this.active?{...this.active}:null};}
  acceptSnapshot(s){if(!s||!Array.isArray(s.occupants)||s.occupants.length>8)return;this.occupants=new Map(s.occupants.filter(x=>typeof x.id==='string'&&typeof x.vesselId==='string'&&[null,'turret-dorsal','engineering'].includes(x.seat)).map(x=>[x.id,x]));if(this.pending)return;const row=this.occupants.get(this.id);if(row?.vesselId!==this.id&&row)this.enterRemote(row.vesselId);if(!row&&this.aboard)this.leaveRemote('Crew boarding ended');if(row?.seat&&S.seated!==row.seat)this.applySeat(row.seat);if(row&&!row.seat&&S.seated)this.stand(false);}
  chooseHome(bodyId){const b=A.world.byId(bodyId);if(!b)return false;this.home={bodyId};try{localStorage.setItem('space-patriot-home-v1',JSON.stringify(this.home));}catch{}F.message='HOME HANGAR · '+b.name;return true;}
  hangarFrame(){const b=A.world.byId(this.home?.bodyId);if(!b)return null;const site=(A.world.primarySite||A.world.site.bind(A.world))(b);return{...site,center:C.add(site.center,C.mul(site.right,-.165))};}
  recallHome(start=true){const b=A.world.byId(this.home?.bodyId);if(!b)return false;if(A.outposts)A.outposts.activate(A.outposts.records.get(b.id+':city:0'));this.release();this.leaveRemote();F.place(b,'surface');const h=this.hangarFrame();F.position=F.vehicle.position=C.add(h.center,C.mul(h.up,F.standHeight()+.001));F.forward=F.vehicle.forward=h.forward.slice();F.up=F.vehicle.up=h.up.slice();F.orthogonalize();F.cameraMode='chase';this.hangarRaised=0;F.message='HOME HANGAR · Press L to raise ship and launch';F.cameraMode='cockpit';if(start)A.start();return true;}
  launchLift(){if(!this.home||this.lift||F.walking||F.bridgeWalk)return false;const h=this.hangarFrame();if(C.length(C.sub(F.vehicle.position,h.center))>.15||!['landed','docked'].includes(F.vehicle.state)){F.message='Return to your home hangar pad to use the lift';return false;}this.lift={elapsed:0,from:F.vehicle.position.slice()};F.message='HANGAR LIFT · RAISING SHIP';return true;}
  updateLift(dt){this.lift.elapsed+=dt;const t=C.clamp(this.lift.elapsed/9,0,1),h=this.hangarFrame();this.hangarRaised=C.smooth(t)*.026;F.position=F.vehicle.position=C.add(h.center,C.mul(h.up,F.standHeight()+.001+this.hangarRaised));F.velocity=[0,0,0];if(t===1){this.lift=null;F.vehicle.state='flight';F.vehicle.gearTarget=0;F.drive.power=true;F.message='LAUNCH CLEAR · Pilot control';}}
  listEncounters(){const body=F.nearest().body,s=A.world.station(body);return['Patrol interception','Convoy distress','Salvage recovery'].map((name,i)=>({id:body.id+':'+i,bodyId:body.id,name,kind:i,reward:[600,900,380][i],position:C.add(s.center,C.add(C.mul(s.forward,8+i*5),C.mul(s.right,(i-1)*4)))}));}
  setEncounter(id){if(A.network.role==='guest'){F.message='The host sets the crew operation';return false;}const e=this.listEncounters().find(e=>e.id===id);if(!e)return false;this.active={...e,status:'travel',kills:B.kills||0};F.message='BEACON SET · '+e.name;return true;}
  flyEncounter(){if(!this.active)return false;const to=this.active.position,from=F.position.slice(),b=A.world.byId(this.active.bodyId);F.cancel();F.walking=false;F.bridgeWalk=false;F.vehicle.state='flight';const duration=C.clamp(C.length(C.sub(to,from))/.7,8,50);F.route={segments:[{duration,label:'OPERATION BEACON APPROACH',at:t=>C.mix(from,to,C.smooth(t))}],index:0,elapsed:0,total:duration,time:0,target:b,orbitOnly:true};A.celestial.followRoute(F.route);return true;}
  beginEncounter(){const e=this.active;if(!e)return;const origin=F.position,forward=F.forward,right=F.right;e.status=e.kind===2?'recovering':'engaged';e.timer=0;B.mission=e.kind===2?'salvage':'space';B.setArmed(e.kind!==2);B.enemies=e.kind===2?[]:Array.from({length:e.kind===1?4:3},(_,i)=>{const p=C.add(origin,C.add(C.mul(forward,.55+i*.22),C.mul(right,(i-1)*.12)));return{id:'encounter-'+e.id+'-'+i,name:e.kind===1?'CONVOY RAIDER':'PATROL HOSTILE',kind:'ship',position:p,anchor:p.slice(),forward:C.mul(forward,-1),up:F.up.slice(),velocity:[0,0,0],hull:100,shield:30,radius:.014,phase:i*1.7,fireIn:3+i};});B.targetId=B.enemies[0]?.id||null;F.message=e.kind===2?'SALVAGE FIELD · Hold position for recovery':'HOSTILE CONTACTS · Operation active';}
  update(dt){this.elapsed+=dt;if(this.aboard){const v=this.vessels().get(this.aboard);if(v)this.attachPose(v);else if(!A.network.links.size)this.leaveRemote('Crew link lost · Returned safely');}if(A.network.role==='host')for(const [id,v]of this.occupants)if(id!==this.id&&!A.network.players.has(id)||v.vesselId!==this.id&&!A.network.players.has(v.vesselId))this.occupants.delete(id);
   const e=this.active;if(!e||A.network.role==='guest')return;const body=A.world.byId(e.bodyId),s=A.world.station(body);e.position=C.add(s.center,C.add(C.mul(s.forward,8+e.kind*5),C.mul(s.right,(e.kind-1)*4)));const dist=C.length(C.sub(F.position,e.position));if(e.status==='travel'&&dist<1&&!F.route)this.beginEncounter();if(e.status==='recovering')e.timer=dist<1?e.timer+dt:0;if(e.status==='engaged'&&B.enemies.length&&B.enemies.every(x=>x.hull<=0)||e.status==='recovering'&&e.timer>=12){e.status='complete';F.ship.credits+=e.reward;F.message='OPERATION COMPLETE · +'+e.reward+' credits';A.toast(F.message);A.economy?.record('Operation completed',e.reward);}}
 }
 A.shipboard=new Shipboard();
 F.navigationBeacons=()=>A.shipboard.listEncounters();
 const tour=S.tourBridge.bind(S);S.tourBridge=(active=!F.bridgeWalk)=>{if(!active&&S.seated)A.shipboard.stand();return tour(active);};
 if(!A.shipboard.home)A.shipboard.chooseHome(A.world.catalog.find(b=>b.name==='Earth').id);
 A.shipboard.recallHome(false);
 const takeoff=F.takeoff.bind(F);F.takeoff=(...args)=>{const h=A.shipboard.hangarFrame();if(h&&!A.shipboard.hangarRaised&&!F.walking&&C.length(C.sub(F.vehicle.position,h.center))<.1)return A.shipboard.launchLift();return takeoff(...args);};
 document.getElementById('start').textContent='Enter your home hangar ↗';
 document.getElementById('start').onclick=()=>{A.shipboard.recallHome();A.focusScene();};
 // Deck stations occupy the visible bridge chairs, with one authoritative seat.
 const oldPlan=C.InteriorLayout;C.InteriorLayout=craft=>{const p=oldPlan(craft);if(!p)return p;const x=p.carrier?4.1:2.8,z=p.carrier?3.7:1.6;p.stations=[{id:'pilot',name:'Pilot',x:0,z:1.8},{id:'engineering',name:'Engineering',x:-x,z},{id:'turret-dorsal',name:'Dorsal remote turret',x,z}];return p;};
 const interact=S.interactInterior.bind(S);S.interactInterior=()=>{if(S.seated){A.shipboard.stand();return true;}return interact();};
 const panel=document.createElement('section');panel.id='shipboardPanel';panel.hidden=true;panel.innerHTML='<h2>Ship stations & home</h2><p>Walk up to a bridge chair and press Z to sit. Press Z again to stand. The ship keeps moving while you walk its deck.</p><div class="station-actions"><button id="walkShip">Leave pilot seat</button><button id="returnSeat">Return to pilot seat</button></div><h3>Crew vessels nearby</h3><div id="boardVessels"></div><h3>Home hangar</h3><select id="homeWorld"></select><button id="chooseHome">Set home</button><p id="homeState"></p><button id="returnHome">Return to home hangar</button><button id="launchHome">Raise ship & launch</button><h3>Orbital clock</h3><select id="orbitScale"><option value="1">Real time · 1×</option><option value="60" selected>Flight pace · 60×</option><option value="3600">Observe orbits · 3600×</option></select><p>Measured orbital periods and Solar System rotations. Exoplanet rotations assume synchronous spin. Distances and epoch layout are adapted for flight.</p>';
 document.body.append(panel);for(const b of A.world.catalog){const o=document.createElement('option');o.value=b.id;o.textContent=b.system+' / '+b.name;panel.querySelector('select').append(o);}if(A.shipboard.home)panel.querySelector('select').value=A.shipboard.home.bodyId;document.getElementById('orbitScale').value=A.celestial.timeScale;
 const close=()=>window.BloxPause?.dismiss();document.getElementById('walkShip').onclick=()=>{close();S.tourBridge(true);};document.getElementById('returnSeat').onclick=()=>{if(A.shipboard.aboard){A.toast('Your friend has the helm');return;}close();S.tourBridge(false);};document.getElementById('chooseHome').onclick=()=>{A.shipboard.chooseHome(document.getElementById('homeWorld').value);document.getElementById('homeState').textContent=F.message;};document.getElementById('returnHome').onclick=()=>{close();A.shipboard.recallHome();};document.getElementById('launchHome').onclick=()=>{close();A.shipboard.launchLift();};document.getElementById('orbitScale').onchange=e=>{A.celestial.setScale(+e.target.value);e.target.value=A.celestial.timeScale;};
 const ops=document.createElement('section');ops.id='scenarioPanel';ops.hidden=true;ops.innerHTML='<h2>Operations beacons</h2><p>Choose a signal, fly to its location, and take part. Rewards are paid when the encounter is completed.</p><div id="encounterList"></div><p id="operationStatus"></p><button id="flyBeacon">Engage beacon autopilot</button>';document.body.append(ops);document.getElementById('flyBeacon').onclick=()=>{close();A.shipboard.flyEncounter();};
 let listKey='';setInterval(()=>{if(!panel.hidden){const rows=document.getElementById('boardVessels');rows.replaceChildren();for(const [id,v]of A.shipboard.vessels()){if(id===A.shipboard.id)continue;const b=document.createElement('button'),c=C.CRAFTS.find(c=>c.id===v.craftId);b.textContent='Board '+(c?.name||'ship')+' · '+Math.round(C.length(C.sub(v.position,F.position))*1000)+' m';b.disabled=!(c?.dimensions[0]>60);b.onclick=()=>{A.shipboard.board(id);close();A.toast(F.message);};rows.append(b);}if(!rows.children.length)rows.textContent='Connect a crew friend to see their ship.';document.getElementById('homeState').textContent=A.shipboard.home?'Assigned: '+A.world.byId(A.shipboard.home.bodyId).name:'Choose a home world.';}if(!ops.hidden){const key=F.nearest().body.id;if(key!==listKey){listKey=key;document.getElementById('encounterList').replaceChildren(...A.shipboard.listEncounters().map(e=>{const b=document.createElement('button');b.textContent=e.name+' · '+e.reward+' credits';b.onclick=()=>{A.shipboard.setEncounter(e.id);A.toast(F.message);};return b;}));}const e=A.shipboard.active;document.getElementById('operationStatus').textContent=e?e.name+' / '+e.status+' / '+C.length(C.sub(e.position,F.position)).toFixed(1)+' km':'No beacon selected';}},300);
})();
