(function(){function init(){if(!window.longway){addEventListener('longway-ready',init,{once:true});return;}
 const A=longway,C=LongwayCore,S=A.society=new C.Society(A);
 const SAVE='space-patriot-society-v1';try{const saved=localStorage.getItem(SAVE);if(saved&&saved.length<500000)S.load(JSON.parse(saved));}catch{}
 const persist=()=>{if(A.combat.authority)try{localStorage.setItem(SAVE,JSON.stringify(S.save()));}catch{}};addEventListener('beforeunload',persist);let lastSave=0;
 const modal=document.createElement('section');modal.id='npcDialogue';modal.hidden=true;modal.innerHTML='<small>LOCAL COMMS / DIRECT CONVERSATION</small><button class="close">Close ×</button><h2></h2><div class="identity"></div><p class="speech"></p><div class="choices"></div>';document.body.append(modal);
 const feed=document.createElement('aside');feed.id='factionRadio';feed.innerHTML='<small>DISTRICT RADIO</small><p></p><button id="talkNPC" hidden>Talk [T]</button>';document.body.append(feed);
 const map=document.createElement('section');map.id='factionMap';map.hidden=true;map.innerHTML='<button class="close">Close ×</button><h2>FRONTIER CONFLICT</h2><p>Squads share targets, suppress approaches and flank. District control changes when one faction survives.</p><div class="relations"></div><div class="worlds"></div><button id="enterConflict">Visit the contested district</button>';document.body.append(map);
 const style=document.createElement('style');style.textContent=`#npcDialogue,#factionMap{position:fixed;z-index:75;left:50%;top:50%;transform:translate(-50%,-50%);width:min(700px,90vw);max-height:85vh;overflow:auto;background:#081419f5;padding:30px;color:#d6e3dd;border:12px solid transparent;border-image:var(--hud-frame) 85 fill stretch}#npcDialogue[hidden],#factionMap[hidden],#factionRadio[hidden]{display:none}#npcDialogue small,#factionRadio small{font-size:9px;letter-spacing:2px;color:#82b3a8}#npcDialogue h2,#factionMap h2{font:500 27px system-ui;margin:18px 0 5px}#npcDialogue .identity{font-size:12px;color:#91acaa}#npcDialogue .speech{font:17px/1.8 Georgia,serif;margin:28px 0;min-height:110px}#npcDialogue .choices{display:grid;gap:8px}#npcDialogue .choices button{text-align:left;padding:12px;font-size:12px}#npcDialogue .close,#factionMap .close{float:right}#factionRadio{position:fixed;left:28px;top:225px;z-index:12;width:280px;padding:14px;background:#081419de;border-left:2px solid #77b3a2}#factionRadio p{font:11px/1.7 system-ui;color:#bdd3cc;margin:8px 0}#factionRadio button{width:100%}#factionMap .relations{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:22px 0}#factionMap .relations div{padding:12px;background:#41605822;font-size:12px}#factionMap .worlds{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:20px}#factionMap .worlds div{font-size:11px;border-bottom:1px solid #71847b33;padding:9px}#factionMap p{font:13px/1.7 system-ui}`;document.head.append(style);
 BloxUI.registerDialog('npcDialogue');BloxUI.registerDialog('factionMap');let person=null,last='',lastPerson='';function draw(topic='greeting'){const found=S.nearestPerson();if(!found||found.person!==person){BloxUI.close();return;}const r=S.conversation(person,topic);if(!r)return;modal.querySelector('h2').textContent=r.name;modal.querySelector('.identity').textContent=r.job+' · '+r.faction+' · Standing '+r.reputation;modal.querySelector('.speech').textContent=r.text;const choices=modal.querySelector('.choices');choices.replaceChildren();for(const [id,text]of [['war','Who is fighting, and how do they operate?'],['world','Tell me about this world.'],['job','Got work for my crew?'],['deliver','Deliver the agreed supplies.']]){const b=document.createElement('button');b.textContent=text;b.onclick=()=>draw(id);choices.append(b);}const story=document.createElement('button');story.textContent='Open the linked investigations · The Long Debt';story.onclick=()=>CampaignUI.open();choices.append(story);}
 function talk(){const npc=S.nearestPerson();if(!npc)return;person=npc.person;BloxUI.open('npcDialogue');draw();}
 modal.querySelector('.close').onclick=()=>BloxUI.close();feed.querySelector('button').onclick=talk;
 addEventListener('keydown',e=>{if(e.code==='KeyT'&&!e.repeat&&!/INPUT|TEXTAREA/.test(e.target.tagName)&&S.nearestPerson()){e.preventDefault();e.stopImmediatePropagation();talk();}},true);
 const button=document.createElement('button');button.textContent='Factions';document.querySelector('.top-actions').append(button);button.onclick=()=>{if(map.hidden){BloxUI.open('factionMap');renderMap();}else BloxUI.close();};map.querySelector('.close').onclick=()=>BloxUI.close();
 function renderMap(){map.querySelector('.relations').replaceChildren();for(const f of C.FACTIONS){const d=document.createElement('div');d.style.borderTop='2px solid '+f.color;d.textContent=f.name+' · '+S.reputation[f.id]+' standing';map.querySelector('.relations').append(d);}map.querySelector('.worlds').replaceChildren();for(const b of A.world.catalog){const d=document.createElement('div'),war=S.wars[b.id];d.textContent=b.name+' / '+(C.FACTIONS.find(f=>f.id===war?.owner)?.name||'Unclaimed')+' · '+(war?.status||'contested');map.querySelector('.worlds').append(d);}}
 map.querySelector('#enterConflict').onclick=()=>{if(!A.combat.authority){A.toast('The host captain chooses the shared district.');return;}const b=A.selected||A.flight.nearest().body,F=A.flight,city=C.CityWorld.forBody(b),build=city.buildings[6];F.place(b,'surface');F.walking=true;F.bridgeWalk=false;F.vehicle.state='onfoot';F.vehicle.transition=null;F.position=C.CityWorld.worldPoint(A.world,b,[build.x,C.CityWorld.BASE+C.CityWorld.EYE,build.z-15]);F.up=A.world.site(b).up.slice();F.forward=C.mul(A.world.site(b).forward,-1);F.viewYaw=F.viewPitch=0;F.orthogonalize();S.enter(b);A.network.broadcastMission();BloxUI.close();A.start();};
 const before=PlanetEngineUI.update;PlanetEngineUI.update=()=>{before();if(performance.now()-lastSave>10000){lastSave=performance.now();persist();}const B=A.combat;feed.hidden=!A.started||B.mission!=='frontier'||A.flight.bridgeWalk;const npc=S.nearestPerson(),radio=S.radio.at(-1);if(radio&&last!==radio.id){last=radio.id;feed.querySelector('p').textContent=radio.speaker+' · '+radio.text;}const bt=feed.querySelector('button');bt.hidden=!npc;if(npc&&lastPerson!==npc.id){lastPerson=npc.id;bt.textContent='T · Talk to '+npc.name;}if(!modal.hidden&&(!npc||npc.person!==person))BloxUI.close();};
}init();})();
